export const FACTORY_ADDRESS = '0xD1b0e186A2B0d602f27cE2e046Fa95BBe9FE6d84' as const;

export const FACTORY_ABI = [
  {
    inputs: [
      { internalType: 'uint256', name: 'createPoolFeeRatio', type: 'uint256' },
      { internalType: 'string', name: 'entityId', type: 'string' },
      { internalType: 'contract RWA', name: 'rwa', type: 'address' },
      { internalType: 'uint256', name: 'expectedHoldAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'expectedRwaAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'priceImpactPercent', type: 'uint256' },
      { internalType: 'uint256', name: 'rewardPercent', type: 'uint256' },
      { internalType: 'uint256', name: 'entryPeriodStart', type: 'uint256' },
      { internalType: 'uint256', name: 'entryPeriodExpired', type: 'uint256' },
      { internalType: 'uint256', name: 'completionPeriodExpired', type: 'uint256' },
      { internalType: 'uint256', name: 'entryFeePercent', type: 'uint256' },
      { internalType: 'uint256', name: 'exitFeePercent', type: 'uint256' },
      { internalType: 'bool', name: 'fixedSell', type: 'bool' },
      { internalType: 'bool', name: 'allowEntryBurn', type: 'bool' },
      { internalType: 'bool', name: 'awaitCompletionExpired', type: 'bool' },
      { internalType: 'bool', name: 'floatingOutTranchesTimestamps', type: 'bool' },
      { internalType: 'uint256[]', name: 'outgoingTranches', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'outgoingTranchTimestamps', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'incomingTranches', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'incomingTrancheExpired', type: 'uint256[]' },
      { internalType: 'address[]', name: 'signers', type: 'address[]' },
      { internalType: 'bytes[]', name: 'signatures', type: 'bytes[]' },
      { internalType: 'uint256', name: 'expired', type: 'uint256' },
    ],
    name: 'deployPool',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;